[package]
name = "spotify-wallpaper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0.203", features = ["derive"] }
serde-xml-rs = "0.6.0"
shellexpand = "3.1.0"
walkdir = "2.5.0"
